// Optional Edge check; prepare .local/inventory-smoke from INVENTORY_SAVE and make_game.
const {chromium}=require(process.env.X4_PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const base=process.env.X4_WEB_URL||'http://127.0.0.1:8765';
  const wait=async()=>{await page.waitForFunction(()=>!busy);};
  const tab=async name=>{await page.locator(`[data-tab=${name}]`).click();await wait();};
  const group=async name=>{await page.getByRole('button',{name}).click();await wait();};
  const row=id=>page.locator('#featureBody tbody tr').filter({hasText:id});
  try{
    await page.goto(base);await page.waitForFunction(()=>token.length>10);await wait();
    page.on('dialog',d=>d.accept());
    await page.locator('#gameSettings').click();
    await page.locator('#gamePath').fill(path.resolve(__dirname,'../.local/inventory-smoke/game'));
    await page.locator('#loadGameData').click();await wait();
    await page.locator('#open').click();
    await page.locator('#file').setInputFiles(path.resolve(__dirname,'../.local/inventory-smoke/save.xml'));
    await page.locator('#moneyAmount').waitFor();await wait();
    await tab('inventory');
    assert.equal(await page.getByRole('combobox',{name:'选择物品持有人'}).locator('option').count(),4);
    assert.equal(await row('inv_training').count(),1);
    assert.equal(await row('paintmod_test').count(),0);
    assert.equal(await row('mod_engine_test').count(),0);
    await page.getByRole('spinbutton',{name:'inv_training 目标数量',exact:true}).fill('5');
    await group(/喷漆 Paint MOD/);
    assert.equal(await row('inv_training').count(),0);
    await row('paintmod_test').getByRole('button',{name:'删除',exact:true}).click();await wait();
    assert.equal(await row('paintmod_test').getByRole('spinbutton').inputValue(),'0');
    await row('paintmod_test').getByRole('button',{name:'取消删除'}).click();await wait();
    assert.equal(await row('paintmod_test').getByRole('spinbutton').inputValue(),'4');
    await row('paintmod_test').getByRole('button',{name:'删除',exact:true}).click();await wait();
    await group(/改装 MOD/);
    assert.equal(await row('mod_engine_test').count(),1);
    assert.equal(await row('paintmod_test').count(),0);
    await group(/其他物品/);
    assert.equal(await row('inv_training').getByRole('spinbutton').inputValue(),'5');
    await page.locator('#stageAll').click();await wait();
    assert.equal(await page.locator('#changeCount').textContent(),'2');
    const holder=page.getByRole('combobox',{name:'选择物品持有人'});
    const crew=await holder.locator('option').filter({hasText:'Captain'}).getAttribute('value');
    const station=await holder.locator('optgroup[label="空间站"] option').getAttribute('value');
    const player=await holder.locator('optgroup[label="玩家"] option').getAttribute('value');
    await holder.selectOption(crew);await wait();
    assert.equal(await row('inv_training').getByRole('spinbutton').inputValue(),'3');
    await holder.selectOption(station);await wait();
    await page.getByRole('combobox',{name:'选择特殊物品',exact:true}).selectOption('inv_training');
    await page.getByRole('spinbutton',{name:'特殊物品目标数量',exact:true}).fill('7');
    await page.getByRole('button',{name:'加入待修改物品'}).click();await wait();
    await page.locator('#stageAll').click();await wait();
    await holder.selectOption(player);await wait();await group(/喷漆 Paint MOD/);
    assert((await row('paintmod_test').textContent()).includes('已暂存删除'));
    await page.locator('#export').click();await page.locator('#exportName').fill('inventory-browser.xml');
    await page.locator('#confirmExport').click();await page.locator('#resultDialog').waitFor();
    const url=await page.locator('#download').getAttribute('href');
    const xml=await(await page.request.get(base+url)).text();
    assert(!xml.includes('ware="paintmod_test"'));
    assert(xml.includes('ware="inv_training" amount="5"'));
    assert(xml.includes('ware="inv_training" amount="3"'));
    assert(xml.includes('ware="inv_training" amount="7"'));
    assert(xml.includes('ware="mod_engine_test" amount="1"'));
    await page.locator('#resultDialog [data-close]').click();
    await page.setViewportSize({width:700,height:850});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    assert.deepEqual(errors,[]);
    console.log('PASS: inventory grouping, delete/cancel, drafts across groups, holder isolation, add, export, narrow layout');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
